### ISSUE TITLE
nsxt_policy_security_policy remove rule comments and does not allow to set it. 

### ISSUE THREAD

**Issue by eltchao** [vmware/terraform-provider-nsxt#1041]
### Describe the bug

When setting a rule using nsxt_policy_security_policy resource. 
It is possible to manage the Policy comments. 

However at the rule level, it is not possible to manage it. In addition to that any comment added manually would be remove and it is impossible to ignore the changes on this parameter. 

### Reproduction steps

1. Create a nsxt_policy_security_policy with a least a rule. 
2. Add a comments parameter under the rule -> creating the resource fails. 
3. Deploy the resource without a comment -> OK
4. Add a comment to the rule in the UI. 
5. Re-run terraform -> Terraform doesn't see the change. 
6. Make an update to the rule and do terraform deploy -> the Comment has been removed. 

### Expected behavior

The rule comments should be manageable under terraform.

**Comment by salv-orlando** [comment]
Hello @eltchao , I believe there are two aspects in your report that need to be considered.

- The comment cannot be specified via Terraform
- A comment added manually to a rule in NSX is then overriden by the next "Terraform apply" command.

For the former it seems that the "notes" attribute,  when specified, causes an error when applying the plan.
Can you please confirm which version of NSX and the Terraform provider you are using?

The latter might happen because Terraform detects a drift in the state and converge it to the one it believes to be the correct one - the one without the comment.

**Comment by annakhm** [comment]
I suspect what causes confusion here is inconsistency between naming - comments on policy are called `Comments`, while on rule they are called `Notes`. This naming was derived from the API spec, and perhaps the provider should have renamed `Notes` field in the same way as UI did. I've tested the `notes` attribute in rule and it works as expected for me.
Please let us know whether this is a naming issue or functional issue. If this is functional issue (i.e. `notes` attribute on rule errors out), please provide configuration and NSX version so that we can reproduce it. Thank you!

**Comment by eltchao** [comment]
@annakhm You are right, I got confused. The UI says "comments" and that's what I was looking for. Thank you for your answer. I am closing the ticket.
