### ISSUE TITLE
Pagination not working on resource "nsxt_vm_tags" and data "nsxt_policy_vm"

### ISSUE THREAD

**Issue by mktgo** [vmware/terraform-provider-nsxt#536]
Hi All,

Looks like pagination isn't working for these 2 resources (and maybe more). We have over 1000 VM's in NSXT and any VM's outside of that first thousand always return with an error of:

```
Unable to find Virtual Machine with name prefix
```

or

```
Unable to find Virtual Machine with ID
```

I have verified that the Machine can be searched for by both name and UUID in the NSXT GUI.  

I had a dig and tracked the issue down. 

resource_nsxt_vm_tags.go
  - func getVMList

This function does not include pagination at all and will only ever return one page of results. I can provide a fix for this if needed.

I tracked the datasource issue to the endpoint used /policy/api/v1/infra/realized-state/virtual-machines. Unless i'm mistaken that endpoint does not return a resultCount or cursor variable (at least on our NSXT version 2.5.1).

Let me know if you need any more information.

Mark

**Comment by annakhm** [comment]
Hello @mktgo, thank you for reporting this! As you have spotted, the platform does not populate pagination values as expected, linked here is a workaround solution.
We generally don't prioritize issues for non-policy resources since those are expected to be deprecated, but we welcome contributions for those.
