### ISSUE TITLE
resource for lb policy monitor

### ISSUE THREAD

**Issue by urraco77** [vmware/terraform-provider-nsxt#578]
Please add resource for lb policy monitor of:
lb_http_monitor
lb_https_monitor
lb_icmp_monitor
lb_passive_monitor
lb_tcp_monitor
lb_udp_monitor

in nsx-t 3.1 the object create with resource:

nsxt_lb_http_monitor
nsxt_lb_https_monitor
nsxt_lb_icmp_monitor
nsxt_lb_passive_monitor
nsxt_lb_tcp_monitor
nsxt_lb_udp_monitor

are no longer visible in policy view

**Comment by walkafwalka** [comment]
@annakhm Can we remove the lifecycle from this one? 'Tis the top upvoted enhancement.

**Comment by sneal** [comment]
To install Tanzu Application Service using the NSX-T policy API I have to workaround this by manually creating the object and reference it elsewhere via a `nsxt_policy_lb_monitor` data element.

**Comment by martinrohrbach** [comment]
@urraco77 
Not sure why you closed this. t's a bit strange to deprecate all manager UI resources but not have the equivalent policy UI resources, so yeah, we're also still waiting for this one to come and there are quite a lot of upvotes as mentioned above.

Then again, maybe all policy UI LB resources will be deprecated next week because advanced LB / AVI will eventually replace the LB ...

**Comment by annakhm** [comment]
I'm reopening this, however note that all LB APIs are deprecated on NSX. This is the reason these are not prioritized in dev.
