### ISSUE TITLE
Support for Installation Workflows

### ISSUE THREAD

**Issue by thadc23** [vmware/terraform-provider-nsxt#64]
Is there any future considerations being given to expanding this provider to actually lay down the Manager, Controllers, and Edges or would the expectation be to use the vSphere provider?

If the latter, where would the logic go to connect the controllers and edges to the manager?

Thanks.

**Comment by avoltmer** [comment]
Assuming you are deploying the manager to vSphere I recommend you use the vSphere provider to deploy the manager .ova. The other items generally would be a new feature request to support installation. Currently the provider is oriented toward logical networking and security.

**Comment by johnuopini** [comment]
Deploying the OVA files using the vsphere provider is quite easy there are a few things however that would be nice to see in this plugin and that i am currently doing via API calls to the manager:

- Register a controller, an edge or an ESXi host into the manager plane, so especially having the the edge and the controller as new resource objects (the OVA can be provided as a parameter potentially)
- Create a T0 router
- Create basic configuration es transport zones

Having these 3 items would make the solution quite complete. I have everything done via python calls already so maybe i can fork and try to create a pull for this, a bit new to GO so not sure if i can make it but will try.

**Comment by aegershman** [comment]
@johnuopini I believe the creation of T0/T1 routers [can be setup as resources](https://www.terraform.io/docs/providers/nsxt/r/logical_tier0_router.html)? Please correct me if I'm off-base.

**Comment by johnuopini** [comment]
@aegershman yes, when i wrote that i didnt see the head repo but just the one in the terraform official site, the one here on GitHub supports T0 resources and T1, still doesnt allow to create Master / Controllers and Edges but afaik 2.5/2.6 might provide this in some way (either through the Master itself thus making the requirement here not useful) or by supporting it directly in TF

**Comment by aegershman** [comment]
Gotcha, just confirming. Yes I also hope that most of the installation & configuration of those components can be represented as terraform resources. I'm opposed to using multiple automation toolchains (like ansible/python scripts calling REST endpoints) vs. keeping the source-of-truth entirely terraform. Thanks @johnuopini 👍

**Comment by Hannes-Work** [comment]
My company operates NSX-T under PKS. We have several PKS foundations and wanted to realize the basic installation (T0 router, T1 infra router, infra segment, IP pools, ...) for these with terraform, because we already manage the DFW and Edge FW configurations with terraform.

Because the terraform provider can not generate any edge systems, we have to do it in a laborious way with api calls. We miss the rollout of the edge VMs, the configuration of the edge VMs (eg. logging server, timeserver, password expiration, ...), configurationof uplinks in the VLAN transport zone and all this things.

We also want to solve the disaster recovery with terraform. Other automation systems require servers or appliances. But if you have to start from scratch to rebuild the infrastructure, then terraform will do this on a simple Linux machine and the  .tf files.

There may be ways to do that with various terraform providers (vSphere, Shell, RESTapi, ...), but that's a cruel thing.

**Comment by annakhm** [comment]
This is considered for next major release

**Comment by annakhm** [comment]
This is now supported, hence closing
