### ISSUE TITLE
nsx_id argument is missing under rule argument on nsxt_policy_gateway_policy and nsxt_policy_security_policy resources

### ISSUE THREAD

**Issue by scharrier-revolve** [vmware/terraform-provider-nsxt#740]
### Is your feature request related to a problem? Please describe.

When a Gateway Policy or a Security Policy with a rule is created, the rule has a generated unique ID (id field in the API), it must be possible to define a custom ID (like the Display Name) for the rule as we can define it for the parent Gateway/Security Policy

### Describe the solution you'd like

Add nsx_id argument under rule argument on nsxt_policy_gateway_policy and nsxt_policy_security_policy resources

**Comment by annakhm** [comment]
For the security policy, the issue is fixed with newly introduced pair of resources
https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_parent_security_policy
https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_security_policy_rule

Those resources are still in Beta but expected to be promoted in next release.

For gateway policy this feature is not available yet, hence keeping this issue open. Sorry for the long wait!

**Comment by chanakanissanka** [comment]
@annakhm Thanks for this update. I would like to check would there is any chance that this will be coming to this resource at some point - https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_security_policy. 

The reason I'm asking this is, that we have 3000+ rules created to spread across 6 policy sets and we have an issue atm since we are not setting NSX_ID , our monitoring and traceability of those rules shifting causing security concerns. 

Any advice on how best we can move to the one you suggest above to  https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_security_policy
or any other possible suggestion to introduce NSX_ID or Path

**Comment by chanakanissanka** [comment]
@annakhm Thanks for the quick response. We have 3000+ rules with old resource block - resource "nsxt_policy_security_policy" "policy_import5" 

We tried creating a new policy set and 3 test rules using the link you provided(The new resource)  and it's giving this error . This is VMC NSX-T env. Are we missing something here ? TF provider version is 3.6.2
Error: Value for unconfigurable attribute
│ 
│   with nsxt_policy_security_policy_rule.rule1,
│   on new_resource_block_test.tf line 26, in resource "nsxt_policy_security_policy_rule" "rule1":
│   26:   nsx_id = 1
│ 
│ Can't configure a value for "nsx_id": its value will be decided
│ automatically based on the result of applying this configuration.
╵
╷
│ Error: Value for unconfigurable attribute
│ 
│   with nsxt_policy_security_policy_rule.rule2,
│   on new_resource_block_test.tf line 40, in resource "nsxt_policy_security_policy_rule" "rule2":
│   40:   nsx_id = 2
│ 
│ Can't configure a value for "nsx_id": its value will be decided
│ automatically based on the result of applying this configuration.

**Comment by annakhm** [comment]
This is a bug, thank you for noticing and reporting! `nsx_id` should be configurable with this resource. We are fixing this.
